### ISSUE TITLE
Device Streaming Mode 'Play Recording' is very slow

### ISSUE THREAD

**Issue by paul-ferragut** [rfilkov/AzureKinectUnityFree#2]
I can load .mkv file but there are playing very slowly, like 1 frame per second. Is it a bug or a setting somewhere?
Thank you!

**Comment by rfilkov** [comment]
Does your recording contain IMU frames?

**Comment by rfilkov** [comment]
Please update from the repo and try again.

**Comment by paul-ferragut** [comment]
Awesome it is working now! thank you for replying so fast
